function saveStereoParameters(stereoParams, filename)
            fw = fopen(filename, 'wt');
            fprintf(fw,'# Camera parameters for prosilica Cameras, Estimated on %s.\r\n\r\n', date());
            fprintf(fw,'camera111_H\r\n');
            K = stereoParams.CameraParameters1.IntrinsicMatrix';
            fprintf(fw,'%f\t%f\t%f\r\n',K(1,1),K(1,2),K(1,3));
            fprintf(fw,'%f\t%f\t%f\r\n',K(2,1),K(2,2),K(2,3));
            fprintf(fw,'%f\t%f\t%f\r\n',K(3,1),K(3,2),K(3,3));            
            F = stereoParams.CameraParameters1.RadialDistortion;
            fprintf(fw,'%f\r\n%f\r\n',F(1),F(2));            
            %fprintf(fw,num2str('));
            RT = [1 0 0 0; 0 1 0 0; 0 0 1 0];
            fprintf(fw,'%f\t%f\t%f\t%f\r\n',RT(1,1),RT(1,2),RT(1,3),RT(1,4));
            fprintf(fw,'%f\t%f\t%f\t%f\r\n',RT(2,1),RT(2,2),RT(2,3),RT(2,4));
            fprintf(fw,'%f\t%f\t%f\t%f\r\n',RT(3,1),RT(3,2),RT(3,3),RT(3,4));
            %fprintf(fw,num2str([1 0 0 0; 0 1 0 0; 0 0 1 0]));
            fprintf(fw,'\r\n\r\ncamera113_H\r\n');
            K = stereoParams.CameraParameters2.IntrinsicMatrix';
            fprintf(fw,'%f\t%f\t%f\r\n',K(1,1),K(1,2),K(1,3));
            fprintf(fw,'%f\t%f\t%f\r\n',K(2,1),K(2,2),K(2,3));
            fprintf(fw,'%f\t%f\t%f\r\n',K(3,1),K(3,2),K(3,3));            
            F = stereoParams.CameraParameters2.RadialDistortion;
            fprintf(fw,'%f\r\n%f\r\n',F(1),F(2));            
            %fprintf(fw,num2str('));
            RT = [stereoParams.RotationOfCamera2', handles.stereoParams.TranslationOfCamera2'];
            fprintf(fw,'%f\t%f\t%f\t%f\r\n',RT(1,1),RT(1,2),RT(1,3),RT(1,4));
            fprintf(fw,'%f\t%f\t%f\t%f\r\n',RT(2,1),RT(2,2),RT(2,3),RT(2,4));
            fprintf(fw,'%f\t%f\t%f\t%f\r\n',RT(3,1),RT(3,2),RT(3,3),RT(3,4));
            fprintf(fw,'\r\n\r\n');
            fclose(fw);
